// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'main-canvas': string;
  'mainCanvas': string;
  'small-canvas': string;
  'smallCanvas': string;
  'wrapper': string;
}
declare const cssExports: CssExports;
export = cssExports;
