// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footer': string;
  'header': string;
  'icon': string;
  'left': string;
  'links': string;
  'name': string;
  'project': string;
  'technologies': string;
  'wrapper': string;
}
declare const cssExports: CssExports;
export = cssExports;
