// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header-red': string;
  'headerRed': string;
}
declare const cssExports: CssExports;
export = cssExports;
