// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header-blue': string;
  'headerBlue': string;
}
declare const cssExports: CssExports;
export = cssExports;
