// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'header': string;
  'sidebar': string;
}
declare const cssExports: CssExports;
export = cssExports;
